name: i14y-dataset-import
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: your-username/i14y-dataset-import
    envs:
      - key: FLASK_SECRET_KEY
        value: ""
        type: SECRET
      - key: JWT_EXPECTED_ISSUER
        value: "https://identity-eiam.eiam.admin.ch/realms/edi_bfs-i14y"
    build_command: pip install -r requirements.txt
    run_command: gunicorn run:app
